import type { TravelAtlasItem } from "@/domain/types";

export const travelAtlas: TravelAtlasItem[] = [
  {
    id: "usvinskie-stolby",
    name: "Усьвинские Столбы",
    region: "Пермский край",
    routeTitle: "Каменная дорога к Усьвинским Столбам",
    anchorPlace: "Усьвинские Столбы",
    nearestTransportHub: "Пермь",
    hotelSearchCity: "Пермь",
    tags: ["cliffs", "railway", "nature", "silence"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "solitude", "road"],
    tarotArchetypes: ["cliffs", "road", "solitude", "mystery"],
    source: "fallback",
    sourceUrl: "https://ru.wikipedia.org/wiki/Усьвинские_Столбы",
    geoUrl: "https://www.tutu.ru/geo/",
  },
  {
    id: "karelia-ruskeala",
    name: "Рускеала",
    region: "Республика Карелия",
    routeTitle: "Мрамор, вода и северная дорога",
    anchorPlace: "Горный парк Рускеала",
    nearestTransportHub: "Сортавала",
    hotelSearchCity: "Сортавала",
    tags: ["water", "stone", "north", "train"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["mystery", "renewal"],
    tarotArchetypes: ["water", "north", "mystery", "road"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/",
  },
  {
    id: "murmansk-teriberka",
    name: "Териберка",
    region: "Мурманская область",
    routeTitle: "Северный край, океан и звезда",
    anchorPlace: "Териберка",
    nearestTransportHub: "Мурманск",
    hotelSearchCity: "Мурманск",
    tags: ["north", "water", "aurora", "edge"],
    season: ["winter", "spring", "autumn"],
    mood: ["mystery", "solitude"],
    tarotArchetypes: ["north", "water", "star", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/",
    geoUrl: "https://www.tutu.ru/geo/",
  },
  {
    id: "kaliningrad",
    name: "Калининградская область",
    region: "Калининградская область",
    routeTitle: "Балтийская прогулка и янтарный свет",
    anchorPlace: "Калининград",
    nearestTransportHub: "Калининград",
    hotelSearchCity: "Калининград",
    tags: ["water", "culture", "food", "sea"],
    season: ["spring", "summer", "autumn"],
    mood: ["culture", "food", "sun"],
    tarotArchetypes: ["water", "culture", "food", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/",
    geoUrl: "https://www.tutu.ru/geo/",
  },
  {
    id: "suzdal",
    name: "Суздаль",
    region: "Владимирская область",
    routeTitle: "Белокаменный город и тихий поворот времени",
    anchorPlace: "Суздаль",
    nearestTransportHub: "Владимир",
    hotelSearchCity: "Суздаль",
    tags: ["culture", "history", "slow"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "renewal"],
    tarotArchetypes: ["culture", "renewal", "solitude"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/",
  },
];
