import type { TravelAtlasItem } from "@/domain/types";

export const travelAtlas: TravelAtlasItem[] = [
  {
    id: "usvinskie-stolby",
    name: "Усьвинские Столбы",
    region: "Пермский край",
    routeTitle: "Каменная дорога к Усьвинским Столбам",
    anchorPlace: "Усьвинские Столбы",
    nearestTransportHub: "Пермь",
    hotelSearchCity: "Пермь",
    tags: ["cliffs", "railway", "nature", "silence"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "solitude", "road"],
    tarotArchetypes: ["cliffs", "road", "solitude", "mystery"],
    source: "fallback",
    sourceUrl: "https://ru.wikipedia.org/wiki/Усьвинские_Столбы",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Каменные столбы обещают путь, где тишина сильнее шума города.",
  },
  {
    id: "kaliningrad-active",
    name: "Калининградская область",
    region: "Калининградская область",
    routeTitle: "Балтийские косы, янтарь и старый Кенигсберг",
    anchorPlace: "Калининград, Светлогорск и Балтийская коса",
    nearestTransportHub: "Калининград",
    hotelSearchCity: "Калининград",
    tags: ["water", "culture", "food", "sea"],
    season: ["spring", "summer", "autumn"],
    mood: ["culture", "food", "sun"],
    tarotArchetypes: ["water", "culture", "food", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/kaliningradskaya-2025",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Балтийский ветер зовет туда, где янтарь хранит память о старом море.",
    routeDays: 6,
    rating: "9,3",
  },
  {
    id: "krasnodar-active",
    name: "Краснодарский край",
    region: "Краснодарский край",
    routeTitle: "Горы, Малая Лаба и черноморский финал",
    anchorPlace: "Гуамское ущелье, Мостовской и Сочи",
    nearestTransportHub: "Минеральные Воды",
    hotelSearchCity: "Краснодар",
    tags: ["sun", "food", "cliffs", "road"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "food", "road"],
    tarotArchetypes: ["sun", "food", "cliffs", "road", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/krasnodarskiy-2025",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Южная карта обещает резкую смену высоты: от горячей земли к горной дороге.",
    routeDays: 6,
    rating: "10",
  },
  {
    id: "hmao-yugra",
    name: "Югра",
    region: "ХМАО — Югра",
    routeTitle: "Таежный север, стойбища и сибирская кухня",
    anchorPlace: "Когалым, Сургут и Ханты-Мансийск",
    nearestTransportHub: "Сургут",
    hotelSearchCity: "Ханты-Мансийск",
    tags: ["north", "food", "culture", "forest"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["mystery", "food", "culture"],
    tarotArchetypes: ["north", "food", "culture", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/hmao",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Северная масть ведет к тайге, где дорогу освещают огни стойбищ.",
    routeDays: 6,
    rating: "9,9",
  },
  {
    id: "murmansk-khibiny",
    name: "Хибины и Кольский север",
    region: "Мурманская область",
    routeTitle: "Заполярное сияние, Хибины и Белое море",
    anchorPlace: "Апатиты, Кандалакша и Кировск",
    nearestTransportHub: "Апатиты",
    hotelSearchCity: "Кировск",
    tags: ["north", "water", "aurora", "mountains"],
    season: ["winter", "spring", "autumn", "summer"],
    mood: ["mystery", "solitude", "dramatic"],
    tarotArchetypes: ["north", "water", "star", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/murmanskaya-2025",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Звезда ложится на север: небо здесь само раскрывает карту сияния.",
    routeDays: 4,
    rating: "9,3",
  },
  {
    id: "arkhangelsk-russian-north",
    name: "Архангельская область",
    region: "Архангельская область",
    routeTitle: "Поморский север, Малые Корелы и Белое море",
    anchorPlace: "Архангельск и Малые Корелы",
    nearestTransportHub: "Архангельск",
    hotelSearchCity: "Архангельск",
    tags: ["north", "culture", "food", "water"],
    season: ["spring", "summer", "autumn"],
    mood: ["culture", "food", "solitude"],
    tarotArchetypes: ["north", "culture", "food", "water"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/arhangelskaya-2025/",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Птица счастья с Русского Севера показывает дорогу к деревянным теремам и белым ночам.",
    rating: "9,3",
  },
  {
    id: "vladivostok",
    name: "Владивосток",
    region: "Приморский край",
    routeTitle: "Мосты, бухты и город на краю материка",
    anchorPlace: "Владивосток, бухта Стеклянная и остров Русский",
    nearestTransportHub: "Владивосток",
    hotelSearchCity: "Владивосток",
    tags: ["water", "food", "road", "sea"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "food", "road"],
    tarotArchetypes: ["water", "food", "road", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/vladivostok",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "На восточной карте море встречает город мостами и соленым ветром.",
    routeDays: 5,
    rating: "10",
  },
  {
    id: "primorye-lighthouses",
    name: "Маяки Приморья",
    region: "Приморский край",
    routeTitle: "Маяки, бухты и тропа к мысу Тобизина",
    anchorPlace: "Остров Русский, Славянка и Находка",
    nearestTransportHub: "Владивосток",
    hotelSearchCity: "Владивосток",
    tags: ["water", "sun", "nature", "road"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "sun", "road"],
    tarotArchetypes: ["water", "sun", "road", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/vladivostok-2",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Маяк в раскладе обещает берег, где решение становится видимым издалека.",
    routeDays: 7,
    rating: "9,0",
  },
  {
    id: "dagestan-canyons",
    name: "Дагестан",
    region: "Республика Дагестан",
    routeTitle: "Сулакский каньон, горные аулы и кавказская кухня",
    anchorPlace: "Махачкала, Хунзах и горные дороги",
    nearestTransportHub: "Махачкала",
    hotelSearchCity: "Махачкала",
    tags: ["cliffs", "culture", "food", "road"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "culture", "food"],
    tarotArchetypes: ["cliffs", "culture", "food", "road"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/dagestan",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Башня указывает на каньоны: здесь высота не пугает, а раскрывает путь.",
  },
  {
    id: "tatarstan-kazan",
    name: "Казань и Татарстан",
    region: "Республика Татарстан",
    routeTitle: "Волга, кремль и татарская гастрономия",
    anchorPlace: "Казань",
    nearestTransportHub: "Казань",
    hotelSearchCity: "Казань",
    tags: ["culture", "food", "water", "city"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "food", "renewal"],
    tarotArchetypes: ["culture", "food", "water", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/tatarstan",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Две культуры сходятся как две реки, и карта выбирает город с сильным вкусом.",
  },
  {
    id: "buryatia-baikal",
    name: "Бурятский Байкал",
    region: "Республика Бурятия",
    routeTitle: "Байкальский лед, дацаны и семейские села",
    anchorPlace: "Улан-Удэ, Максимиха и Святой Нос",
    nearestTransportHub: "Улан-Удэ",
    hotelSearchCity: "Улан-Удэ",
    tags: ["water", "culture", "north", "food"],
    season: ["winter", "spring", "summer", "autumn"],
    mood: ["mystery", "culture", "renewal"],
    tarotArchetypes: ["water", "culture", "north", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/buryatiya",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/baikal/",
    oracleHook: "Вода Байкала становится зеркалом: в нем видна не дорога, а её смысл.",
    routeDays: 4,
  },
  {
    id: "altai-chuysky",
    name: "Горный Алтай",
    region: "Республика Алтай",
    routeTitle: "Чуйский тракт, Катунь и горные перевалы",
    anchorPlace: "Горно-Алтайск, Чуйский тракт и Телецкое озеро",
    nearestTransportHub: "Горно-Алтайск",
    hotelSearchCity: "Горно-Алтайск",
    tags: ["cliffs", "road", "nature", "water"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "road", "renewal"],
    tarotArchetypes: ["road", "cliffs", "water", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/altai_republic/",
    oracleHook: "Колесница выбирает тракт, где каждый поворот похож на новую жизнь.",
  },
  {
    id: "baikal-irkutsk",
    name: "Байкал",
    region: "Иркутская область",
    routeTitle: "Ольхон, Малое Море и ледяная прозрачность",
    anchorPlace: "Иркутск и Ольхон",
    nearestTransportHub: "Иркутск",
    hotelSearchCity: "Иркутск",
    tags: ["water", "north", "nature", "solitude"],
    season: ["winter", "summer", "autumn"],
    mood: ["mystery", "solitude", "renewal"],
    tarotArchetypes: ["water", "north", "mystery", "solitude"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/baikal/",
    oracleHook: "Зеркальная вода забирает лишние мысли и возвращает точный ответ.",
  },
  {
    id: "komi-manpupuner",
    name: "Маньпупунёр",
    region: "Республика Коми",
    routeTitle: "Плато каменных исполинов и Югыд Ва",
    anchorPlace: "Маньпупунёр и национальный парк Югыд Ва",
    nearestTransportHub: "Сыктывкар",
    hotelSearchCity: "Сыктывкар",
    tags: ["cliffs", "north", "nature", "solitude"],
    season: ["summer", "autumn", "winter"],
    mood: ["dramatic", "solitude", "mystery"],
    tarotArchetypes: ["cliffs", "north", "solitude", "mystery"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/komi_republic/",
    oracleHook: "Каменные великаны Коми стоят как старшие арканы: молча, но безошибочно.",
  },
  {
    id: "tuva-por-bazhyn",
    name: "Тыва",
    region: "Республика Тыва",
    routeTitle: "Степи, аржааны и крепость Пор-Бажын",
    anchorPlace: "Кызыл, Дус-Холь и Пор-Бажын",
    nearestTransportHub: "Кызыл",
    hotelSearchCity: "Кызыл",
    tags: ["culture", "mystery", "nature", "solitude"],
    season: ["spring", "summer", "autumn"],
    mood: ["mystery", "solitude", "renewal"],
    tarotArchetypes: ["culture", "mystery", "solitude", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/tuva/",
    oracleHook: "Там, где степь встречает горы, расклад становится почти шаманским.",
  },
  {
    id: "khakasia-open-air",
    name: "Хакасия",
    region: "Республика Хакасия",
    routeTitle: "Курганы, озера и древние каменные знаки",
    anchorPlace: "Абакан, Шира и Белый Июс",
    nearestTransportHub: "Абакан",
    hotelSearchCity: "Абакан",
    tags: ["culture", "mystery", "sun", "nature"],
    season: ["spring", "summer", "autumn"],
    mood: ["mystery", "culture", "sun"],
    tarotArchetypes: ["culture", "mystery", "sun", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/respublika_hakasiya/",
    oracleHook: "Древние камни Хакасии отвечают тем, кто умеет читать тени.",
  },
  {
    id: "ingushetia-towers",
    name: "Ингушетия",
    region: "Республика Ингушетия",
    routeTitle: "Башенные комплексы и Джейрахское ущелье",
    anchorPlace: "Магас, Эгикал и Вовнушки",
    nearestTransportHub: "Назрань",
    hotelSearchCity: "Магас",
    tags: ["cliffs", "culture", "history", "mountains"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "culture", "mystery"],
    tarotArchetypes: ["cliffs", "culture", "mystery", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/ingushetia/",
    oracleHook: "Горные башни стоят как стражи расклада: они зовут к памяти рода и высоте.",
  },
  {
    id: "chechnya-kezenoy-am",
    name: "Чечня",
    region: "Чеченская Республика",
    routeTitle: "Кезеной-Ам, башни и горные дороги",
    anchorPlace: "Грозный, Шали и Кезеной-Ам",
    nearestTransportHub: "Грозный",
    hotelSearchCity: "Грозный",
    tags: ["water", "cliffs", "culture", "road"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["dramatic", "culture", "renewal"],
    tarotArchetypes: ["water", "cliffs", "culture", "road"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/chechnya/",
    oracleHook: "Горное озеро в раскладе показывает спокойствие после смелого поворота.",
  },
  {
    id: "tyumen-thermal",
    name: "Тюмень",
    region: "Тюменская область",
    routeTitle: "Термальные источники и купеческая Сибирь",
    anchorPlace: "Тюмень",
    nearestTransportHub: "Тюмень",
    hotelSearchCity: "Тюмень",
    tags: ["renewal", "food", "culture", "water"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["renewal", "food", "culture"],
    tarotArchetypes: ["renewal", "food", "culture", "water"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/tyumen/",
    oracleHook: "Горячая вода Тюмени смывает усталость дороги и возвращает силы.",
  },
  {
    id: "suzdal",
    name: "Суздаль",
    region: "Владимирская область",
    routeTitle: "Белокаменный город и тихий поворот времени",
    anchorPlace: "Суздаль",
    nearestTransportHub: "Владимир",
    hotelSearchCity: "Суздаль",
    tags: ["culture", "history", "slow"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "renewal", "solitude"],
    tarotArchetypes: ["culture", "renewal", "solitude"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/suzdal/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/suzdal/article/putevoditel-po-suzdalyu/",
    oracleHook: "Суздаль ложится тихой картой: здесь время не давит, а разговаривает.",
  },
  {
    id: "karelia-ruskeala",
    name: "Рускеала",
    region: "Республика Карелия",
    routeTitle: "Мрамор, вода и северная дорога",
    anchorPlace: "Горный парк Рускеала",
    nearestTransportHub: "Сортавала",
    hotelSearchCity: "Сортавала",
    tags: ["water", "stone", "north", "train"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["mystery", "renewal", "road"],
    tarotArchetypes: ["water", "north", "mystery", "road"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Мраморный каньон отражает карту в воде, и путь становится северным.",
  },
  {
    id: "yamal-tundra",
    name: "Ямал",
    region: "Ямало-Ненецкий АО",
    routeTitle: "Полярная ночь и тундра на краю света",
    anchorPlace: "Салехард и полуостров Ямал",
    nearestTransportHub: "Салехард",
    hotelSearchCity: "Салехард",
    tags: ["north", "tundra", "arctic", "nenets"],
    season: ["summer", "autumn", "winter"],
    mood: ["mystery", "solitude", "north"],
    tarotArchetypes: ["north", "star", "solitude", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/yamal",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Ямал открывает небо целиком, и полярная ночь оставляет путника наедине со звездой.",
  },
  {
    id: "magadan-kolyma",
    name: "Магадан",
    region: "Магаданская область",
    routeTitle: "Дорога на Колыме и берег Охотского моря",
    anchorPlace: "Магадан и бухта Нагаева",
    nearestTransportHub: "Магадан",
    hotelSearchCity: "Магадан",
    tags: ["north", "road", "far-east", "sea"],
    season: ["summer", "autumn", "winter"],
    mood: ["solitude", "mystery", "road"],
    tarotArchetypes: ["north", "road", "star", "solitude"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/magadan",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Магадан лежит в конце самой долгой дороги, там, где тишина и северное сияние говорят громче слов.",
  },
  {
    id: "sheregesh-snow",
    name: "Шерегеш",
    region: "Кемеровская область",
    routeTitle: "Снежный курорт Горной Шории",
    anchorPlace: "Шерегеш и гора Зелёная",
    nearestTransportHub: "Новокузнецк",
    hotelSearchCity: "Шерегеш",
    tags: ["winter", "ski", "mountains", "snow"],
    season: ["winter", "spring"],
    mood: ["renewal", "sun", "road"],
    tarotArchetypes: ["road", "renewal", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/kemerovo",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Шерегеш встречает ярким горным солнцем на снегу такой глубины, что каждый спуск похож на обновление.",
  },
  {
    id: "taganay-ridge",
    name: "Таганай",
    region: "Челябинская область",
    routeTitle: "Каменные реки и хребты Таганая",
    anchorPlace: "Таганай и Златоуст",
    nearestTransportHub: "Челябинск",
    hotelSearchCity: "Златоуст",
    tags: ["mountains", "hiking", "stone-river", "nature"],
    season: ["winter", "spring", "summer", "autumn"],
    mood: ["solitude", "renewal", "road"],
    tarotArchetypes: ["road", "renewal", "solitude"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/chelyabinsk",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Таганай ведёт по каменной реке к хребту, где одиночество превращается в ясность.",
  },
  {
    id: "kalmykia-steppe",
    name: "Калмыкия",
    region: "Республика Калмыкия",
    routeTitle: "Степь, звёзды и Золотая обитель Будды",
    anchorPlace: "Элиста и Золотая обитель Будды Шакьямуни",
    nearestTransportHub: "Элиста",
    hotelSearchCity: "Элиста",
    tags: ["steppe", "buddhism", "culture", "stars"],
    season: ["spring", "autumn", "winter"],
    mood: ["mystery", "solitude", "culture"],
    tarotArchetypes: ["star", "solitude", "culture", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/kalmykia",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Калмыкия открывает степь без края, и ночью здесь звезда становится ближе, чем где-либо.",
  },
  {
    id: "pskov-kremlin",
    name: "Псков",
    region: "Псковская область",
    routeTitle: "Кремль, Печоры и вода на границе Руси",
    anchorPlace: "Псков и Псково-Печерский монастырь",
    nearestTransportHub: "Псков",
    hotelSearchCity: "Псков",
    tags: ["culture", "history", "kremlin", "monastery"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "mystery", "water"],
    tarotArchetypes: ["culture", "water", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/pskov",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Псков стоит на границе воды и веры, там, где кремль хранит память о каждом рубеже.",
  },
  {
    id: "seliger-lake",
    name: "Селигер",
    region: "Тверская область",
    routeTitle: "Озёрный край Селигера и тихая вода",
    anchorPlace: "Осташков и озеро Селигер",
    nearestTransportHub: "Тверь",
    hotelSearchCity: "Осташков",
    tags: ["lake", "water", "forest", "retreat"],
    season: ["spring", "summer", "autumn"],
    mood: ["solitude", "renewal", "water"],
    tarotArchetypes: ["water", "solitude", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/tver",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Селигер расстилает воду между лесами, и здесь одиночество звучит только плеском весла.",
  },
  {
    id: "mari-el-fairytale",
    name: "Марий Эл",
    region: "Республика Марий Эл",
    routeTitle: "Сказочная набережная и лесная вера мари",
    anchorPlace: "Йошкар-Ола и набережная Брюгге",
    nearestTransportHub: "Йошкар-Ола",
    hotelSearchCity: "Йошкар-Ола",
    tags: ["culture", "architecture", "river", "mari"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "mystery", "water"],
    tarotArchetypes: ["culture", "mystery", "water"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/mari-el",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Марий Эл строит на реке город-сказку, а в окрестных рощах до сих пор жива вера леса.",
  },
  {
    id: "udmurtia-forest",
    name: "Удмуртия",
    region: "Удмуртская Республика",
    routeTitle: "Оружейный город и лесные святилища удмуртов",
    anchorPlace: "Ижевск и Ижевский пруд",
    nearestTransportHub: "Ижевск",
    hotelSearchCity: "Ижевск",
    tags: ["culture", "food", "forest", "udmurt"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "mystery", "food"],
    tarotArchetypes: ["culture", "mystery", "food"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/udmurtia",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Удмуртия хранит лесные святилища и стол, где угощение значит не меньше, чем слово.",
  },
  {
    id: "yaroslavl-volga",
    name: "Ярославль",
    region: "Ярославская область",
    routeTitle: "Волга, купола и сердце Золотого кольца",
    anchorPlace: "Ярославль и набережная Волги",
    nearestTransportHub: "Ярославль",
    hotelSearchCity: "Ярославль",
    tags: ["culture", "volga", "golden-ring", "history"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "renewal", "water"],
    tarotArchetypes: ["culture", "water", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/yaroslavl",
    geoUrl: "https://www.tutu.ru/geo/",
    oracleHook: "Ярославль встречает Волгу куполами, и здесь золотое кольцо замыкается обновлением.",
  },
];
