import type { TravelAtlasItem } from "@/domain/types";

// Guide facts (seasonWindow/stops/highlights/oneLine, plus filling in the
// remaining routeDays/rating and correcting sourceUrl/geoUrl) merged
// one-time from data/tutu-guides.json -- see that file for the raw
// collector output and provenance notes. Nothing here reads data/ at
// runtime; this is a static edit of the compiled atlas.
export const travelAtlas: TravelAtlasItem[] = [
  {
    id: "usvinskie-stolby",
    name: "Усьвинские Столбы",
    region: "Пермский край",
    routeTitle: "Каменная дорога к Усьвинским Столбам",
    anchorPlace: "Усьвинские Столбы",
    nearestTransportHub: "Пермь",
    hotelSearchCity: "Пермь",
    tags: ["cliffs", "railway", "nature", "silence"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "solitude", "road"],
    tarotArchetypes: ["cliffs", "road", "solitude", "mystery"],
    // The original link pointed at Wikipedia -- not Tutu data at all -- so
    // this was the atlas's one "fallback" entry. The collector found the
    // real Tutu route behind it (provereno.tutu.ru/perm-2), so both the URL
    // and the source tier move: this destination is a provereno.tutu route
    // now, not a fallback.
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/perm-2",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/perm_krai/",
    oracleHook: "Каменные столбы обещают путь, где тишина сильнее шума города.",
    routeDays: 6,
    rating: "8,8",
    seasonWindow: "круглый год",
    stops: [
      "Пермь",
      "Архитектурно-этнографический музей «Хохловка»",
      "Красновишерск",
      "Чердынь",
      "Усьвинские столбы",
      "Каменный город",
    ],
    highlights: ["Скалы над Усьвой", "Кунгурская пещера", "Пермские старые заводы"],
    oneLine: "Маршрут ведёт от Перми к северным городкам, пещере и каменным стенам Усьвы.",
  },
  {
    id: "kaliningrad-active",
    name: "Калининградская область",
    region: "Калининградская область",
    routeTitle: "Балтийские косы, янтарь и старый Кенигсберг",
    anchorPlace: "Калининград, Светлогорск и Балтийская коса",
    nearestTransportHub: "Калининград",
    hotelSearchCity: "Калининград",
    tags: ["water", "culture", "food", "sea"],
    season: ["spring", "summer", "autumn"],
    mood: ["culture", "food", "sun"],
    tarotArchetypes: ["water", "culture", "food", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/kaliningradskaya-2025",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/kaliningrad_oblast/",
    oracleHook: "Балтийский ветер зовет туда, где янтарь хранит память о старом море.",
    routeDays: 6,
    rating: "9,3",
    seasonWindow: "май-октябрь",
    stops: ["Калининград", "Светлогорск", "Зеленоградск", "Балтийская коса", "Роминтенская пуща", "Гусев"],
    highlights: ["Балтийские косы", "Прусская архитектура", "Веломаршруты и леса"],
    oneLine: "Балтика здесь соединяет косы, кирхи, курортные города и активные маршруты.",
  },
  {
    id: "krasnodar-active",
    name: "Краснодарский край",
    region: "Краснодарский край",
    routeTitle: "Горы, Малая Лаба и черноморский финал",
    anchorPlace: "Гуамское ущелье, Мостовской и Сочи",
    nearestTransportHub: "Минеральные Воды",
    hotelSearchCity: "Краснодар",
    tags: ["sun", "food", "cliffs", "road"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "food", "road"],
    tarotArchetypes: ["sun", "food", "cliffs", "road", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/krasnodarskiy-2025",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/krasnodar_krai/",
    oracleHook: "Южная карта обещает резкую смену высоты: от горячей земли к горной дороге.",
    routeDays: 6,
    rating: "10",
    seasonWindow: "май–октябрь",
    stops: ["Минеральные Воды", "Мостовской", "Псебай", "Гуамское ущелье", "Краснодар", "Сочи"],
    highlights: ["Горы и ущелья", "Термальные места", "Сочи и Skypark"],
    oneLine: "Южный маршрут смешивает ущелья, курорты, термы, Краснодар и сочинский экстрим.",
  },
  {
    id: "hmao-yugra",
    name: "Югра",
    region: "ХМАО — Югра",
    routeTitle: "Таежный север, стойбища и сибирская кухня",
    anchorPlace: "Когалым, Сургут и Ханты-Мансийск",
    nearestTransportHub: "Сургут",
    hotelSearchCity: "Ханты-Мансийск",
    tags: ["north", "food", "culture", "forest"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["mystery", "food", "culture"],
    tarotArchetypes: ["north", "food", "culture", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/hmao",
    // No geoUrl: the collector found no accurate geo page for Yugra/HMAO
    // (only a Khanty-Mansiysk page, not a regional one) -- see
    // data/tutu-guides.json's own note for this id. Carrying the old bare
    // "/geo/" placeholder forward would be worse than no link at all.
    oracleHook: "Северная масть ведет к тайге, где дорогу освещают огни стойбищ.",
    routeDays: 6,
    rating: "9,9",
    seasonWindow: "круглосуточно",
    stops: [
      "Когалым",
      "Русскинская",
      "Сургут",
      "Этнографическое стойбище «Хантыйский дворик»",
      "Шапша",
      "Ханты-Мансийск",
    ],
    highlights: ["Культура ханты", "Таёжные маршруты", "Югорские музеи"],
    oneLine: "Югра раскрывается через стойбища, северные города, музеи и таёжные впечатления.",
  },
  {
    id: "murmansk-khibiny",
    name: "Хибины и Кольский север",
    region: "Мурманская область",
    routeTitle: "Заполярное сияние, Хибины и Белое море",
    anchorPlace: "Апатиты, Кандалакша и Кировск",
    nearestTransportHub: "Апатиты",
    hotelSearchCity: "Кировск",
    tags: ["north", "water", "aurora", "mountains"],
    season: ["winter", "spring", "autumn", "summer"],
    mood: ["mystery", "solitude", "dramatic"],
    tarotArchetypes: ["north", "water", "star", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/murmanskaya-2025",
    // No geoUrl: no accurate geo page for Murmansk region/Khibiny was found
    // (only a Murmansk-city page) -- see data/tutu-guides.json's note.
    oracleHook: "Звезда ложится на север: небо здесь само раскрывает карту сияния.",
    routeDays: 4,
    rating: "9,3",
    seasonWindow: "круглый год",
    stops: ["Апатиты", "Кандалакша", "Кандалакшский залив", "сопка Волосяная", "Кировск", "Долина Малого Вудъявра"],
    highlights: ["Хибины", "Кольские заливы", "Северные тропы"],
    oneLine: "Кольский север даёт горы, заливы, долины и смену арктического настроения.",
  },
  {
    id: "arkhangelsk-russian-north",
    name: "Архангельская область",
    region: "Архангельская область",
    routeTitle: "Поморский север, Малые Корелы и Белое море",
    anchorPlace: "Архангельск и Малые Корелы",
    nearestTransportHub: "Архангельск",
    hotelSearchCity: "Архангельск",
    tags: ["north", "culture", "food", "water"],
    season: ["spring", "summer", "autumn"],
    mood: ["culture", "food", "solitude"],
    tarotArchetypes: ["north", "culture", "food", "water"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/arhangelskaya-2025/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/arkhangelsk_oblast/",
    oracleHook: "Птица счастья с Русского Севера показывает дорогу к деревянным теремам и белым ночам.",
    routeDays: 5,
    rating: "9,3",
    seasonWindow: "май-октябрь",
    stops: ["Архангельск", "Малые Корелы", "пароход «Н. В. Гоголь»", "Северодвинск", "остров Ягры", "село Ломоносово"],
    highlights: ["Русский Север", "Деревянное зодчество", "Пароходный круиз"],
    oneLine: "Северный маршрут ведёт через Архангельск, деревянные музеи, острова и поморские места.",
  },
  {
    id: "vladivostok",
    name: "Владивосток",
    region: "Приморский край",
    routeTitle: "Мосты, бухты и город на краю материка",
    anchorPlace: "Владивосток, бухта Стеклянная и остров Русский",
    nearestTransportHub: "Владивосток",
    hotelSearchCity: "Владивосток",
    tags: ["water", "food", "road", "sea"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "food", "road"],
    tarotArchetypes: ["water", "food", "road", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/vladivostok",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/vladivostok/",
    oracleHook: "На восточной карте море встречает город мостами и соленым ветром.",
    routeDays: 5,
    rating: "10",
    seasonWindow: "май—октябрь",
    stops: [
      "Бухта Стеклянная",
      "Владивосток",
      "Остров Русский",
      "Картодром «Змеинка»",
      "Приморский Сафари-парк",
      "игорная зона «Приморье»",
    ],
    highlights: ["Море и мосты", "Остров Русский", "Приморские развлечения"],
    oneLine: "Владивосток цепляет морем, мостами, островами и ощущением края материка.",
  },
  {
    id: "primorye-lighthouses",
    name: "Маяки Приморья",
    region: "Приморский край",
    routeTitle: "Маяки, бухты и тропа к мысу Тобизина",
    anchorPlace: "Остров Русский, Славянка и Находка",
    nearestTransportHub: "Владивосток",
    hotelSearchCity: "Владивосток",
    tags: ["water", "sun", "nature", "road"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "sun", "road"],
    tarotArchetypes: ["water", "sun", "road", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/vladivostok-2",
    // No geoUrl: no accurate geo page for Primorsky Krai itself was found
    // (only the Vladivostok page, already used by the sibling entry above).
    oracleHook: "Маяк в раскладе обещает берег, где решение становится видимым издалека.",
    routeDays: 7,
    rating: "9,0",
    seasonWindow: "май–октябрь",
    stops: ["Владивосток", "Остров Русский", "Славянка", "Андреевка", "Южно-Морской", "Находка"],
    highlights: ["Приморские маяки", "Береговые посёлки", "Гастрофестиваль"],
    oneLine: "Маршрут идёт вдоль моря, маяков, бухт, посёлков и приморской кухни.",
  },
  {
    id: "dagestan-canyons",
    name: "Дагестан",
    region: "Республика Дагестан",
    routeTitle: "Сулакский каньон, горные аулы и кавказская кухня",
    anchorPlace: "Махачкала, Хунзах и горные дороги",
    nearestTransportHub: "Махачкала",
    hotelSearchCity: "Махачкала",
    tags: ["cliffs", "culture", "food", "road"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "culture", "food"],
    tarotArchetypes: ["cliffs", "culture", "food", "road"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/dagestan",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/dagestan/",
    oracleHook: "Башня указывает на каньоны: здесь высота не пугает, а раскрывает путь.",
    routeDays: 4,
    rating: "8,8",
    seasonWindow: "май—ноябрь",
    stops: ["Махачкала", "Сулакский район", "Чиркейское водохранилище", "Ирганайское водохранилище", "Хунзах", "Дербент"],
    highlights: ["Каньоны и горы", "Водохранилища", "Дербент и крепости"],
    oneLine: "Дагестан собирает каньоны, горные сёла, древний Дербент и каспийский воздух.",
  },
  {
    id: "tatarstan-kazan",
    name: "Казань и Татарстан",
    region: "Республика Татарстан",
    routeTitle: "Волга, кремль и татарская гастрономия",
    anchorPlace: "Казань",
    nearestTransportHub: "Казань",
    hotelSearchCity: "Казань",
    tags: ["culture", "food", "water", "city"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "food", "renewal"],
    tarotArchetypes: ["culture", "food", "water", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/tatarstan",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/tatarstan/",
    oracleHook: "Две культуры сходятся как две реки, и карта выбирает город с сильным вкусом.",
    routeDays: 5,
    rating: "9,0",
    seasonWindow: "апрель–октябрь",
    stops: ["Лаишево", "Семрук", "Голубые озёра", "Волжская тропа", "Юрьевская пещера", "гора Лобач"],
    highlights: ["Волжские тропы", "Голубые озёра", "Пещера и гора"],
    oneLine: "Татарстан в этом маршруте соединяет воду, тропы, пещеру, кинолокации и Волгу.",
  },
  {
    id: "buryatia-baikal",
    name: "Бурятский Байкал",
    region: "Республика Бурятия",
    routeTitle: "Байкальский лед, дацаны и семейские села",
    anchorPlace: "Улан-Удэ, Максимиха и Святой Нос",
    nearestTransportHub: "Улан-Удэ",
    hotelSearchCity: "Улан-Удэ",
    tags: ["water", "culture", "north", "food"],
    season: ["winter", "spring", "summer", "autumn"],
    mood: ["mystery", "culture", "renewal"],
    tarotArchetypes: ["water", "culture", "north", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/buryatiya",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/buryatia/",
    oracleHook: "Вода Байкала становится зеркалом: в нем видна не дорога, а её смысл.",
    routeDays: 4,
    rating: "9,2",
    seasonWindow: "февраль–апрель",
    stops: [
      "Улан-Удэ",
      "Максимиха",
      "Забайкальский национальный парк",
      "Баргузинская долина",
      "Иволгинский дацан",
      "село Десятниково",
    ],
    highlights: ["Байкальский лёд", "Дацаны", "Баргузинская долина"],
    oneLine: "Бурятский Байкал даёт лёд, степи, дацаны, старые сёла и широкие виды.",
  },
  {
    id: "altai-chuysky",
    name: "Горный Алтай",
    region: "Республика Алтай",
    routeTitle: "Чуйский тракт, Катунь и горные перевалы",
    anchorPlace: "Горно-Алтайск, Чуйский тракт и Телецкое озеро",
    nearestTransportHub: "Горно-Алтайск",
    hotelSearchCity: "Горно-Алтайск",
    tags: ["cliffs", "road", "nature", "water"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "road", "renewal"],
    tarotArchetypes: ["road", "cliffs", "water", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/altai_republic/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/altai_republic/",
    oracleHook: "Колесница выбирает тракт, где каждый поворот похож на новую жизнь.",
    // No routeDays/rating: this entry's source is a regional geo guide, not
    // a single rated route -- the page names no overall duration or score.
    seasonWindow: "конец апреля, с начала июня до начала сентября",
    stops: ["Республика Алтай", "Горно-Алтайск", "Чуйский тракт", "Чемал", "Манжерок", "Телецкое озеро"],
    highlights: ["Чуйский тракт", "Горные походы", "Петроглифы и курганы"],
    oneLine: "Горный Алтай зовёт дорогами через хребты, активным отдыхом и древними следами.",
  },
  {
    id: "baikal-irkutsk",
    name: "Байкал",
    region: "Иркутская область",
    routeTitle: "Ольхон, Малое Море и ледяная прозрачность",
    anchorPlace: "Иркутск и Ольхон",
    nearestTransportHub: "Иркутск",
    hotelSearchCity: "Иркутск",
    tags: ["water", "north", "nature", "solitude"],
    season: ["winter", "summer", "autumn"],
    mood: ["mystery", "solitude", "renewal"],
    tarotArchetypes: ["water", "north", "mystery", "solitude"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/baikal/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/baikal/",
    oracleHook: "Зеркальная вода забирает лишние мысли и возвращает точный ответ.",
    seasonWindow: "с середины июля по середину сентября; с середины февраля по конец марта",
    stops: ["Байкал", "остров Ольхон", "мыс Бурхан", "Иркутск", "Улан-Удэ", "Малое Море"],
    highlights: ["Самое глубокое озеро", "Ольхон и мыс Бурхан", "Лёд и нерпа"],
    oneLine: "Байкал цепляет масштабом, чистой водой, островами, льдом и почти морским характером.",
  },
  {
    id: "komi-manpupuner",
    name: "Маньпупунёр",
    region: "Республика Коми",
    routeTitle: "Плато каменных исполинов и Югыд Ва",
    anchorPlace: "Маньпупунёр и национальный парк Югыд Ва",
    nearestTransportHub: "Сыктывкар",
    hotelSearchCity: "Сыктывкар",
    tags: ["cliffs", "north", "nature", "solitude"],
    season: ["summer", "autumn", "winter"],
    mood: ["dramatic", "solitude", "mystery"],
    tarotArchetypes: ["cliffs", "north", "solitude", "mystery"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/komi_republic/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/komi_republic/",
    oracleHook: "Каменные великаны Коми стоят как старшие арканы: молча, но безошибочно.",
    seasonWindow: "с июня по сентябрь",
    stops: ["Маньпупунёр", "Национальный парк-заповедник «Югыд Ва»", "Гора Манарага", "Воркута", "Водопад Буредан", "Село Ыб"],
    highlights: ["Столбы выветривания", "Северная тайга", "Труднодоступные маршруты"],
    oneLine: "Коми привлекает дикими северными ландшафтами, плато Маньпупунёр и походной тишиной.",
  },
  {
    id: "tuva-por-bazhyn",
    name: "Тыва",
    region: "Республика Тыва",
    routeTitle: "Степи, аржааны и крепость Пор-Бажын",
    anchorPlace: "Кызыл, Дус-Холь и Пор-Бажын",
    nearestTransportHub: "Кызыл",
    hotelSearchCity: "Кызыл",
    tags: ["culture", "mystery", "nature", "solitude"],
    season: ["spring", "summer", "autumn"],
    mood: ["mystery", "solitude", "renewal"],
    tarotArchetypes: ["culture", "mystery", "solitude", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/tuva/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/tuva/",
    oracleHook: "Там, где степь встречает горы, расклад становится почти шаманским.",
    seasonWindow: "с середины июня до конца лета",
    stops: ["Убсунурская котловина", "Озеро Чагытай", "Солёное озеро Дус-Холь", "Крепость Пор-Бажын", "озеро Тере-Холь", "Храм Устуу-Хурээ"],
    highlights: ["Дикая степь", "Пор-Бажын на острове", "Горячие аржааны"],
    oneLine: "Тыва звучит как далёкая степь с озёрами, аржаанами, буддийскими храмами и Пор-Бажыном.",
  },
  {
    id: "khakasia-open-air",
    name: "Хакасия",
    region: "Республика Хакасия",
    routeTitle: "Курганы, озера и древние каменные знаки",
    anchorPlace: "Абакан, Шира и Белый Июс",
    nearestTransportHub: "Абакан",
    hotelSearchCity: "Абакан",
    tags: ["culture", "mystery", "sun", "nature"],
    season: ["spring", "summer", "autumn"],
    mood: ["mystery", "culture", "sun"],
    tarotArchetypes: ["culture", "mystery", "sun", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/respublika_hakasiya/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/respublika_hakasiya/",
    oracleHook: "Древние камни Хакасии отвечают тем, кто умеет читать тени.",
    seasonWindow: "с середины июня до третьей декады августа",
    stops: ["Шира", "Белый Июс", "Аскиз", "Саяногорск", "Абакан", "Озеро Шира"],
    highlights: ["Музей под открытым небом", "Петроглифы", "Озёра и сплавы"],
    oneLine: "Хакасия собирает древние камни, озёра, реки и южносибирские маршруты.",
  },
  {
    id: "ingushetia-towers",
    name: "Ингушетия",
    region: "Республика Ингушетия",
    routeTitle: "Башенные комплексы и Джейрахское ущелье",
    anchorPlace: "Магас, Эгикал и Вовнушки",
    nearestTransportHub: "Назрань",
    hotelSearchCity: "Магас",
    tags: ["cliffs", "culture", "history", "mountains"],
    season: ["spring", "summer", "autumn"],
    mood: ["dramatic", "culture", "mystery"],
    tarotArchetypes: ["cliffs", "culture", "mystery", "renewal"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/ingushetia/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/ingushetia/",
    oracleHook: "Горные башни стоят как стражи расклада: они зовут к памяти рода и высоте.",
    seasonWindow: "с апреля по октябрь",
    stops: ["Эгикал", "Башенный комплекс Хамхи", "Таргим", "храм Тхаба-Ерды", "Джейрахское ущелье", "Горнолыжный курорт «Армхи»"],
    highlights: ["Средневековые башни", "Горные ущелья", "Джейрахские виды"],
    oneLine: "Ингушетия держится на башнях, ущельях, древних аулах и резкой горной красоте.",
  },
  {
    id: "chechnya-kezenoy-am",
    name: "Чечня",
    region: "Чеченская Республика",
    routeTitle: "Кезеной-Ам, башни и горные дороги",
    anchorPlace: "Грозный, Шали и Кезеной-Ам",
    nearestTransportHub: "Грозный",
    hotelSearchCity: "Грозный",
    tags: ["water", "cliffs", "culture", "road"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["dramatic", "culture", "renewal"],
    tarotArchetypes: ["water", "cliffs", "culture", "road"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/chechnya/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/chechnya/",
    oracleHook: "Горное озеро в раскладе показывает спокойствие после смелого поворота.",
    // No seasonWindow either: the source page names no overall season for
    // this one, on top of no routeDays/rating -- see data/tutu-guides.json.
    stops: [
      "Мечеть «Гордость мусульман»",
      "Ипподром в Гудермесе",
      "Ушкалойские башни-близнецы",
      "Нихалойские водопады",
      "Горнолыжный курорт «Ведучи»",
      "Озеро Кезеной-Ам",
    ],
    highlights: ["Башни и ущелья", "Кезеной-Ам", "Водопады и горы"],
    oneLine: "Чечня на странице раскрыта через мечети, башни, водопады, Ведучи и озеро Кезеной-Ам.",
  },
  {
    id: "tyumen-thermal",
    name: "Тюмень",
    region: "Тюменская область",
    routeTitle: "Термальные источники и купеческая Сибирь",
    anchorPlace: "Тюмень",
    nearestTransportHub: "Тюмень",
    hotelSearchCity: "Тюмень",
    tags: ["renewal", "food", "culture", "water"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["renewal", "food", "culture"],
    tarotArchetypes: ["renewal", "food", "culture", "water"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/tyumen/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/tyumen/",
    oracleHook: "Горячая вода Тюмени смывает усталость дороги и возвращает силы.",
    seasonWindow: "летние месяцы",
    stops: ["Тюмень", "река Тура", "Аэропорт «Рощино»", "Транссибирская железнодорожная магистраль", "ЛетоЛето"],
    highlights: ["Термальные источники", "Купеческие усадьбы", "Сибирская история"],
    oneLine: "Тюмень сочетает старую Сибирь, термальные воды, набережную и городскую инфраструктуру.",
  },
  {
    id: "suzdal",
    name: "Суздаль",
    region: "Владимирская область",
    routeTitle: "Белокаменный город и тихий поворот времени",
    anchorPlace: "Суздаль",
    nearestTransportHub: "Владимир",
    hotelSearchCity: "Суздаль",
    tags: ["culture", "history", "slow"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "renewal", "solitude"],
    tarotArchetypes: ["culture", "renewal", "solitude"],
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/suzdal/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/suzdal/",
    oracleHook: "Суздаль ложится тихой картой: здесь время не давит, а разговаривает.",
    // No seasonWindow: the source page names no overall season for this one.
    stops: ["Суздаль", "река Каменка", "Золотое кольцо России", "Суздальский кремль", "Щурово городище", "Владимир"],
    highlights: ["Древнерусская архитектура", "Медовуха", "Тихий город у Каменки"],
    oneLine: "Суздаль цепляет древними монастырями, деревянным зодчеством и спокойствием малого города.",
  },
  {
    id: "karelia-ruskeala",
    name: "Рускеала",
    region: "Республика Карелия",
    routeTitle: "Мрамор, вода и северная дорога",
    anchorPlace: "Горный парк Рускеала",
    nearestTransportHub: "Сортавала",
    hotelSearchCity: "Сортавала",
    tags: ["water", "stone", "north", "train"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["mystery", "renewal", "road"],
    tarotArchetypes: ["water", "north", "mystery", "road"],
    // The original link was the generic geo index (no specific region), so
    // the collector went looking and found the actual Karelia geo page --
    // still geo.tutu (not a step up in source tier, unlike Усьвинские
    // Столбы above), just the correct URL for this tier.
    source: "geo.tutu",
    sourceUrl: "https://www.tutu.ru/geo/rossiya/kurort/karelia/",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/karelia/",
    oracleHook: "Мраморный каньон отражает карту в воде, и путь становится северным.",
    seasonWindow: "круглый год",
    stops: ["Кижи", "Валаам", "Горный парк «Рускеала»", "Мраморный каньон", "Водопад Кивач", "Вулкан Гирвас"],
    highlights: ["Рускеала и мрамор", "Кижи и Валаам", "Карельские водопады"],
    oneLine: "Карелия ведёт к Рускеале, островам, водопадам, древним петроглифам и северной кухне.",
  },
  {
    id: "yamal-tundra",
    name: "Ямал",
    region: "Ямало-Ненецкий АО",
    routeTitle: "Полярная ночь и тундра на краю света",
    anchorPlace: "Салехард и полуостров Ямал",
    nearestTransportHub: "Салехард",
    hotelSearchCity: "Салехард",
    tags: ["north", "tundra", "arctic", "nenets"],
    season: ["summer", "autumn", "winter"],
    mood: ["mystery", "solitude", "north"],
    tarotArchetypes: ["north", "star", "solitude", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/yamal",
    // No geoUrl: no accurate geo page for Yamal/YaNAO was found.
    oracleHook: "Ямал открывает небо целиком, и полярная ночь оставляет путника наедине со звездой.",
    routeDays: 6,
    rating: "7,6",
    seasonWindow: "август–сентябрь, декабрь, март–апрель",
    stops: ["Салехард", "Горнокнязевск", "Разъезд Глухариный", "Нефритовая долина", "Массив Янгана-Пэ", "национальный парк «Ингилор»"],
    highlights: ["Тундра и Полярный Урал", "Северные стойбища", "Нацпарк Ингилор"],
    oneLine: "Ямал даёт тундру, полярные дороги, Салехард и суровые маршруты к Ингилору.",
  },
  {
    id: "magadan-kolyma",
    name: "Магадан",
    region: "Магаданская область",
    routeTitle: "Дорога на Колыме и берег Охотского моря",
    anchorPlace: "Магадан и бухта Нагаева",
    nearestTransportHub: "Магадан",
    hotelSearchCity: "Магадан",
    tags: ["north", "road", "far-east", "sea"],
    season: ["summer", "autumn", "winter"],
    mood: ["solitude", "mystery", "road"],
    tarotArchetypes: ["north", "road", "star", "solitude"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/magadan",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/magadan_oblast/",
    oracleHook: "Магадан лежит в конце самой долгой дороги, там, где тишина и северное сияние говорят громче слов.",
    routeDays: 4,
    rating: "9,0",
    seasonWindow: "июль–сентябрь",
    stops: ["Мыс Нюкля", "Магадан", "бухта Нагаева", "Кавинская долина", "Комплекс «Снегорка»"],
    highlights: ["Колымская природа", "Магаданские бухты", "Фестиваль рыбалки"],
    oneLine: "Магаданский маршрут смешивает бухты, Колыму, рыбалку, долины и северный город.",
  },
  {
    id: "sheregesh-snow",
    name: "Шерегеш",
    region: "Кемеровская область",
    routeTitle: "Снежный курорт Горной Шории",
    anchorPlace: "Шерегеш и гора Зелёная",
    nearestTransportHub: "Новокузнецк",
    hotelSearchCity: "Шерегеш",
    tags: ["winter", "ski", "mountains", "snow"],
    season: ["winter", "spring"],
    mood: ["renewal", "sun", "road"],
    tarotArchetypes: ["road", "renewal", "sun"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/kemerovo",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/sheregesh/",
    oracleHook: "Шерегеш встречает ярким горным солнцем на снегу такой глубины, что каждый спуск похож на обновление.",
    routeDays: 5,
    rating: "9,2",
    seasonWindow: "круглый год",
    stops: ["Новокузнецк", "Шерегеш", "Таштагол", "Усть-Кабырза", "Усть-Анзас"],
    highlights: ["Шерегеш", "Горная Шория", "Снежный курорт"],
    oneLine: "Кузбасс на странице ведёт от Новокузнецка к Шерегешу и шорским посёлкам.",
  },
  {
    id: "taganay-ridge",
    name: "Таганай",
    region: "Челябинская область",
    routeTitle: "Каменные реки и хребты Таганая",
    anchorPlace: "Таганай и Златоуст",
    nearestTransportHub: "Челябинск",
    hotelSearchCity: "Златоуст",
    tags: ["mountains", "hiking", "stone-river", "nature"],
    season: ["winter", "spring", "summer", "autumn"],
    mood: ["solitude", "renewal", "road"],
    tarotArchetypes: ["road", "renewal", "solitude"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/chelyabinsk",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/chelyabinsk_oblast/",
    oracleHook: "Таганай ведёт по каменной реке к хребту, где одиночество превращается в ясность.",
    routeDays: 5,
    rating: "8,4",
    seasonWindow: "круглый год",
    stops: ["Челябинск", "Сатка", "Большие притёсы", "Златоуст", "национальный парк «Таганай»", "Магнитогорск"],
    highlights: ["Таганай", "Горные притёсы", "Уральские города"],
    oneLine: "Южный Урал соединяет Челябинск, Таганай, Златоуст, Сатку и индустриальные виды.",
  },
  {
    id: "kalmykia-steppe",
    name: "Калмыкия",
    region: "Республика Калмыкия",
    routeTitle: "Степь, звёзды и Золотая обитель Будды",
    anchorPlace: "Элиста и Золотая обитель Будды Шакьямуни",
    nearestTransportHub: "Элиста",
    hotelSearchCity: "Элиста",
    tags: ["steppe", "buddhism", "culture", "stars"],
    season: ["spring", "autumn", "winter"],
    mood: ["mystery", "solitude", "culture"],
    tarotArchetypes: ["star", "solitude", "culture", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/kalmykia",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/kalmykia/",
    oracleHook: "Калмыкия открывает степь без края, и ночью здесь звезда становится ближе, чем где-либо.",
    routeDays: 4,
    rating: "8,8",
    seasonWindow: "апрель-ноябрь",
    stops: ["Элиста", "Адык", "заповедник «Чёрные земли»", "Булуктара", "Ики-Бурульский район", "этнопарк «Церен»"],
    highlights: ["Степь и сайгаки", "Буддийская Элиста", "Этнопарк"],
    oneLine: "Калмыкия раскрывается степью, буддийской столицей, заповедником и этническими стоянками.",
  },
  {
    id: "pskov-kremlin",
    name: "Псков",
    region: "Псковская область",
    routeTitle: "Кремль, Печоры и вода на границе Руси",
    anchorPlace: "Псков и Псково-Печерский монастырь",
    nearestTransportHub: "Псков",
    hotelSearchCity: "Псков",
    tags: ["culture", "history", "kremlin", "monastery"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "mystery", "water"],
    tarotArchetypes: ["culture", "water", "mystery"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/pskov",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/pskov_oblast/",
    oracleHook: "Псков стоит на границе воды и веры, там, где кремль хранит память о каждом рубеже.",
    routeDays: 4,
    rating: "7,7",
    seasonWindow: "круглый год",
    stops: ["Псков", "Великие Луки", "Остров", "Изборск", "Мальская долина", "Печоры"],
    highlights: ["Крепости и монастыри", "Изборск и Печоры", "Псковская история"],
    oneLine: "Псковский маршрут держится на крепостях, монастырях, старых городах и долинах.",
  },
  {
    id: "seliger-lake",
    name: "Селигер",
    region: "Тверская область",
    routeTitle: "Озёрный край Селигера и тихая вода",
    anchorPlace: "Осташков и озеро Селигер",
    nearestTransportHub: "Тверь",
    hotelSearchCity: "Осташков",
    tags: ["lake", "water", "forest", "retreat"],
    season: ["spring", "summer", "autumn"],
    mood: ["solitude", "renewal", "water"],
    tarotArchetypes: ["water", "solitude", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/tver",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/seliger/",
    oracleHook: "Селигер расстилает воду между лесами, и здесь одиночество звучит только плеском весла.",
    routeDays: 2,
    rating: "9,0",
    seasonWindow: "круглый год",
    stops: ["Куженкино", "Осташков", "Торжок", "Селигер"],
    highlights: ["Озеро Селигер", "Осташков", "Торжок"],
    oneLine: "Короткий тверской маршрут ведёт к Селигеру, Осташкову, Торжку и тихой воде.",
  },
  {
    id: "mari-el-fairytale",
    name: "Марий Эл",
    region: "Республика Марий Эл",
    routeTitle: "Сказочная набережная и лесная вера мари",
    anchorPlace: "Йошкар-Ола и набережная Брюгге",
    nearestTransportHub: "Йошкар-Ола",
    hotelSearchCity: "Йошкар-Ола",
    tags: ["culture", "architecture", "river", "mari"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "mystery", "water"],
    tarotArchetypes: ["culture", "mystery", "water"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/mari-el",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/mari_el/",
    oracleHook: "Марий Эл строит на реке город-сказку, а в окрестных рощах до сих пор жива вера леса.",
    routeDays: 4,
    rating: "9,3",
    seasonWindow: "май—октябрь",
    stops: ["Шоруньжа", "Йошкар-Ола", "Козьмодемьянск", "Экоферма «ЗаАзяково»"],
    highlights: ["Йошкар-Ола", "Марийская культура", "Экоферма"],
    oneLine: "Марий Эл соединяет сказочную городскую архитектуру, этнику, Волгу и деревенский отдых.",
  },
  {
    id: "udmurtia-forest",
    name: "Удмуртия",
    region: "Удмуртская Республика",
    routeTitle: "Оружейный город и лесные святилища удмуртов",
    anchorPlace: "Ижевск и Ижевский пруд",
    nearestTransportHub: "Ижевск",
    hotelSearchCity: "Ижевск",
    tags: ["culture", "food", "forest", "udmurt"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "mystery", "food"],
    tarotArchetypes: ["culture", "mystery", "food"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/udmurtia",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/udmurtia/",
    oracleHook: "Удмуртия хранит лесные святилища и стол, где угощение значит не меньше, чем слово.",
    routeDays: 4,
    rating: "9,3",
    seasonWindow: "май – октябрь",
    stops: ["Ижевск", "село Чутырь", "поселок Игра", "деревня Сеп", "Глазов", "Воткинск"],
    highlights: ["Удмуртские сёла", "Иднакар", "Лесные туркомплексы"],
    oneLine: "Удмуртия в маршруте даёт Ижевск, старые городища, деревни, лесные базы и Воткинск.",
  },
  {
    id: "yaroslavl-volga",
    name: "Ярославль",
    region: "Ярославская область",
    routeTitle: "Волга, купола и сердце Золотого кольца",
    anchorPlace: "Ярославль и набережная Волги",
    nearestTransportHub: "Ярославль",
    hotelSearchCity: "Ярославль",
    tags: ["culture", "volga", "golden-ring", "history"],
    season: ["spring", "summer", "autumn", "winter"],
    mood: ["culture", "renewal", "water"],
    tarotArchetypes: ["culture", "water", "renewal"],
    source: "provereno.tutu",
    sourceUrl: "https://provereno.tutu.ru/yaroslavl",
    geoUrl: "https://www.tutu.ru/geo/rossiya/kurort/yaroslavl_oblast/",
    oracleHook: "Ярославль встречает Волгу куполами, и здесь золотое кольцо замыкается обновлением.",
    routeDays: 3,
    rating: "8,8",
    seasonWindow: "круглый год",
    stops: ["Ярославль", "Гаврилов Ям", "Рыбинск", "Смирново", "Поречье-Рыбное", "Ломы"],
    highlights: ["Волга и старые города", "Рыбинск", "Ярославская провинция"],
    oneLine: "Ярославская область ведёт по Волге, малым городам, усадебным местам и спокойным дорогам.",
  },
];
