// Candidate list for the "Откуда" suggest field's autocomplete dropdown.
//
// Deliberately separate from `travelAtlas` (atlas.ts): the atlas is curated
// *destinations* the tarot draw can offer, matched elsewhere against the
// departure city only to exclude "you're already there" trips (see
// homeCity.ts). This list answers a different question -- "where do
// travellers set out from" -- so it is the population/hub-weighted set of
// major Russian cities a traveller is likely typing, not the 31-item
// destination set. The two lists are expected to overlap in places (Москва,
// Казань...) without being the same list.
//
// Plain data, not TravelAtlasItem: the suggest field only ever needs a
// display string, never anchorPlace/nearestTransportHub/hotelSearchCity.
export const DEPARTURE_CITIES: readonly string[] = [
  "Москва",
  "Санкт-Петербург",
  "Новосибирск",
  "Екатеринбург",
  "Казань",
  "Нижний Новгород",
  "Челябинск",
  "Красноярск",
  "Самара",
  "Уфа",
  "Ростов-на-Дону",
  "Краснодар",
  "Омск",
  "Воронеж",
  "Пермь",
  "Волгоград",
  "Саратов",
  "Тюмень",
  "Тольятти",
  "Барнаул",
  "Ижевск",
  "Ульяновск",
  "Иркутск",
  "Хабаровск",
  "Ярославль",
  "Владивосток",
  "Махачкала",
  "Томск",
  "Оренбург",
  "Кемерово",
  "Новокузнецк",
  "Рязань",
  "Астрахань",
  "Набережные Челны",
  "Пенза",
  "Липецк",
  "Киров",
  "Чебоксары",
  "Балашиха",
  "Калининград",
  "Тула",
  "Курск",
  "Севастополь",
  "Сочи",
  "Ставрополь",
  "Улан-Удэ",
  "Тверь",
  "Магнитогорск",
  "Иваново",
  "Брянск",
  "Белгород",
  "Сургут",
  "Владимир",
  "Архангельск",
  "Калуга",
  "Смоленск",
  "Волжский",
  "Курган",
  "Череповец",
  "Вологда",
  "Саранск",
  "Якутск",
  "Петрозаводск",
  "Мурманск",
  "Йошкар-Ола",
  "Нижневартовск",
  "Кострома",
  "Новороссийск",
  "Таганрог",
  "Сыктывкар",
  "Нальчик",
  "Симферополь",
  "Псков",
  "Великий Новгород",
  "Горно-Алтайск",
  "Кызыл",
  "Ханты-Мансийск",
  "Салехард",
  "Анадырь",
  "Южно-Сахалинск",
  "Петропавловск-Камчатский",
  "Магадан",
] as const;
