import type { TarotCardDefinition } from "@/domain/types";

export const tarotCards: TarotCardDefinition[] = [
  {
    id: "fool", number: 0, name: "Шут", image: "/tarot/00-fool.webp",
    archetypes: ["road", "renewal", "sun"], transport: ["avia"],
    meaning: "шаг в пустоту без плана — и он оказывается верным",
    meaningReversed: "шаг сделан слишком рано, дорога потребует осторожности",
  },
  {
    id: "magician", number: 1, name: "Маг", image: "/tarot/01-magician.webp",
    archetypes: ["culture", "mystery", "renewal"], transport: ["avia"],
    meaning: "всё нужное для поездки уже под рукой",
    meaningReversed: "замысел красив, но детали ещё не собраны",
  },
  {
    id: "priestess", number: 2, name: "Жрица", image: "/tarot/02-priestess.webp",
    archetypes: ["mystery", "water", "solitude"], transport: ["railway"],
    meaning: "место откроется только тому, кто помолчит",
    meaningReversed: "тайна закрывается, ответ придёт позже",
  },
  {
    id: "empress", number: 3, name: "Императрица", image: "/tarot/03-empress.webp",
    archetypes: ["food", "sun", "renewal"], transport: ["bus", "etrain"],
    meaning: "земля щедра: вкус, тепло и полные руки",
    meaningReversed: "изобилие обманчиво, брать придётся понемногу",
  },
  {
    id: "emperor", number: 4, name: "Император", image: "/tarot/04-emperor.webp",
    archetypes: ["culture", "cliffs"], transport: ["bus"],
    meaning: "камень, порядок и крепкие стены",
    meaningReversed: "жёсткий план мешает увидеть место",
  },
  {
    id: "hierophant", number: 5, name: "Иерофант", image: "/tarot/05-hierophant.webp",
    archetypes: ["culture", "mystery"], transport: ["bus", "railway", "etrain"],
    meaning: "дорога к старой традиции и её хранителям",
    meaningReversed: "обряд без смысла, стоит искать своё",
  },
  {
    id: "lovers", number: 6, name: "Влюблённые", image: "/tarot/06-lovers.webp",
    archetypes: ["culture", "food", "water"], transport: ["railway", "bus", "etrain"],
    meaning: "место для близости, прогулок и красивого выбора",
    meaningReversed: "выбор откладывается, спутник тянет в другую сторону",
  },
  {
    id: "chariot", number: 7, name: "Колесница", image: "/tarot/07-chariot.webp",
    archetypes: ["road", "renewal"], transport: ["avia"],
    meaning: "путь складывается через движение и смену горизонта",
    meaningReversed: "рывок не выходит, дорога сопротивляется",
  },
  {
    id: "strength", number: 8, name: "Сила", image: "/tarot/08-strength.webp",
    archetypes: ["sun", "cliffs", "road"], transport: ["bus"],
    meaning: "мягкое упорство одолеет длинный перегон",
    meaningReversed: "сил меньше, чем кажется, маршрут стоит укоротить",
  },
  {
    id: "hermit", number: 9, name: "Отшельник", image: "/tarot/09-hermit.webp",
    archetypes: ["solitude", "mystery", "cliffs"], transport: ["railway", "etrain"],
    meaning: "дорога к тишине и высокому месту",
    meaningReversed: "одиночество тяготит, нужен попутчик",
  },
  {
    id: "wheel", number: 10, name: "Колесо Фортуны", image: "/tarot/10-wheel.webp",
    archetypes: ["road", "mystery"], transport: ["railway", "bus"],
    meaning: "маршрут сам поворачивает в нужную сторону",
    meaningReversed: "колесо встало, расписание переиграет планы",
  },
  {
    id: "justice", number: 11, name: "Справедливость", image: "/tarot/11-justice.webp",
    archetypes: ["culture", "north"], transport: ["bus", "etrain"],
    meaning: "прямая дорога и честный расчёт",
    meaningReversed: "цена и ценность не сходятся",
  },
  {
    id: "hanged", number: 12, name: "Повешенный", image: "/tarot/12-hanged.webp",
    archetypes: ["solitude", "water", "mystery"], transport: ["railway", "etrain"],
    meaning: "время в пути замедлится, и это подарок",
    meaningReversed: "задержка без смысла, ожидание утомит",
  },
  {
    id: "death", number: 13, name: "Смерть", image: "/tarot/13-death.webp",
    archetypes: ["renewal", "north", "mystery"], transport: ["railway"],
    meaning: "переход: прежнее остаётся на перроне",
    meaningReversed: "старое цепляется, отпустить пока не выходит",
  },
  {
    id: "temperance", number: 14, name: "Умеренность", image: "/tarot/14-temperance.webp",
    archetypes: ["water", "food", "renewal"], transport: ["railway", "avia"],
    meaning: "ровный ход, смешение вкусов и мера во всём",
    meaningReversed: "перебор в планах, день придётся разгрузить",
  },
  {
    id: "devil", number: 15, name: "Дьявол", image: "/tarot/15-devil.webp",
    archetypes: ["cliffs", "mystery", "food"], transport: ["bus"],
    meaning: "тянет туда, где неудобно и очень хочется",
    meaningReversed: "соблазн отпускает, дорога становится проще",
  },
  {
    id: "tower", number: 16, name: "Башня", image: "/tarot/16-tower.webp",
    archetypes: ["cliffs", "renewal"], transport: ["avia"],
    meaning: "камень, высота и резкая перемена взгляда",
    meaningReversed: "обвал случился раньше, теперь строят заново",
  },
  {
    id: "star", number: 17, name: "Звезда", image: "/tarot/17-star.webp",
    archetypes: ["north", "water", "mystery"], transport: ["avia"],
    meaning: "северный свет, вода и надежда",
    meaningReversed: "свет тусклый, ориентир придётся искать самому",
  },
  {
    id: "moon", number: 18, name: "Луна", image: "/tarot/18-moon.webp",
    archetypes: ["north", "water", "solitude", "mystery"], transport: ["railway"],
    meaning: "ночная дорога, туман и то, что видно только впотьмах",
    meaningReversed: "туман рассеивается, страх был напрасным",
  },
  {
    id: "sun", number: 19, name: "Солнце", image: "/tarot/19-sun.webp",
    archetypes: ["sun", "food", "renewal"], transport: ["avia"],
    meaning: "тепло, вкус и открытая дорога",
    meaningReversed: "солнце печёт, радость придётся поискать в тени",
  },
  {
    id: "judgement", number: 20, name: "Суд", image: "/tarot/20-judgement.webp",
    archetypes: ["culture", "renewal"], transport: ["railway", "avia"],
    meaning: "старые истории возвращаются новым смыслом",
    meaningReversed: "прошлое зовёт назад, а идти нужно вперёд",
  },
  {
    id: "world", number: 21, name: "Мир", image: "/tarot/21-world.webp",
    archetypes: ["road", "culture", "sun", "star"], transport: ["avia"],
    meaning: "круг замыкается на самой дальней точке",
    meaningReversed: "круг не закрыт, поездка станет первой из двух",
  },
];
